### ISSUE TITLE
Don't display the disclaimer if the mission is being previewed from the 3DEN editor

### ISSUE THREAD

**Issue by Esmeray6** [Nomas-X/AET_AUX#15]
There are many situations where I just want to check a loadout or locally test stuff like weapon control, visibility of gear on players/AI during gameplay, and such.

But having to view the disclaimer every time I restart the mission gets irritating, so my suggestion is as follows:
Don't display the disclaimer if the mission is being previewed from the 3DEN editor. If I need to test disclaimer changes, I can host the mission in local MP.

**Comment by Nomas-X** [comment]
Will be working on this once done with the plant importer and maybe the loadout handler.

**Comment by Nomas-X** [comment]
This should be resolved now thanks to @OverlordZorn. He got sick of it while debugging and fixed it.
